# Имя нашего полного CI/CD процесса
name: CI/CD - Сборка, публикация и развертывание

# Триггер: запускать при пуше в ветку "main"
on:
  push:
    branches: [ "main" ]

# Задачи, которые нужно выполнить
jobs:
  # Задача №1: Сборка и публикация образа
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Скачивание кода
        uses: actions/checkout@v3

      - name: Вход в GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Сборка и публикация образа
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # --- ИСПРАВЛЕНО ЗДЕСЬ ---
          tags: ghcr.io/${{ toLowerCase(github.repository) }}:latest

  # Задача №2: Развертывание на сервере
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Развертывание на сервере
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # --- ИСПРАВЛЕНО ЗДЕСЬ ---
            docker pull ghcr.io/${{ toLowerCase(github.repository) }}:latest
            
            docker stop logsapp || true
            docker rm logsapp || true
            
            # --- И ИСПРАВЛЕНО ЗДЕСЬ ---
            docker run -d --restart always -p 80:3000 --name logsapp ghcr.io/${{ toLowerCase(github.repository) }}:latest
            
            docker image prune -af