name: CI/CD - Сборка, публикация и развертывание

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Скачивание кода
        uses: actions/checkout@v3

      - name: Вход в GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Сборка и публикация образа
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # --- УБРАНА ФУНКЦИЯ toLowerCase ---
          tags: ghcr.io/${{ github.repository }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Развертывание на сервере
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # --- УБРАНА ФУНКЦИЯ toLowerCase ---
            docker pull ghcr.io/${{ github.repository }}:latest
            
            docker stop logsapp || true
            docker rm logsapp || true
            
            # --- УБРАНА ФУНКЦИЯ toLowerCase ---
            docker run -d --restart always -p 80:3000 --name logsapp ghcr.io/${{ github.repository }}:latest
            
            docker image prune -af
